NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/ca.py.aaa.com-cert.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/ca.py.aaa.com-cert.pem
    OrganizationalUnitIdentifier: peer
