# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

volumes:
  orderer.aaa.com:
  peer0.py.aaa.com:
  peer1.py.aaa.com:
  peer0.cpp.aaa.com:
  peer1.cpp.aaa.com:

networks:
  byfn:

services:

  orderer.aaa.com:
    extends:
      file:   base/docker-compose-base.yaml
      service: orderer.aaa.com
    container_name: orderer.aaa.com
    networks:
      - byfn

  peer0.py.aaa.com:
    container_name: peer0.py.aaa.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.py.aaa.com
    networks:
      - byfn

  peer1.py.aaa.com:
    container_name: peer1.py.aaa.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer1.py.aaa.com
    networks:
      - byfn

  peer0.cpp.aaa.com:
    container_name: peer0.cpp.aaa.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.cpp.aaa.com
    networks:
      - byfn

  peer1.cpp.aaa.com:
    container_name: peer1.cpp.aaa.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer1.cpp.aaa.com
    networks:
      - byfn

  cli:
    container_name: cli
    image: hyperledger/fabric-tools:latest
    tty: true
    stdin_open: true
    environment:
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      #- CORE_LOGGING_LEVEL=DEBUG
      - CORE_LOGGING_LEVEL=INFO
      - CORE_PEER_ID=cli
      - CORE_PEER_ADDRESS=peer0.py.aaa.com:7051
      - CORE_PEER_LOCALMSPID=pyMSP
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/py.aaa.com/peers/peer0.py.aaa.com/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/py.aaa.com/peers/peer0.py.aaa.com/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/py.aaa.com/peers/peer0.py.aaa.com/tls/ca.crt
      - CORE_PEERmspCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/py.aaa.com/users/Admin@py.aaa.com/msp
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash
    volumes:
        - /var/run/:/host/var/run/
        - ./../chaincode/:/opt/gopath/src/github.com/chaincode
        - ./crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
        - ./scripts:/opt/gopath/src/github.com/hyperledger/fabric/peer/scripts/
        - ./channel-artifacts:/opt/gopath/src/github.com/hyperledger/fabric/peer/channel-artifacts
    depends_on:
      - orderer.aaa.com
      - peer0.py.aaa.com
      - peer1.py.aaa.com
      - peer0.cpp.aaa.com
      - peer1.cpp.aaa.com
    networks:
      - byfn
